# Generated by Django 3.1.3 on 2023-05-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_auto_20230521_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='contact',
            new_name='f_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
    ]
